/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
  const api: typeof import('./src/lib/api').api;
}

// for vue template auto import
import { UnwrapRef } from 'vue';
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly api: UnwrapRef<(typeof import('./src/lib/api'))['api']>;
  }
}
