/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// Generated by Pathstrider. Do not edit.

import type { ClientMethod, InferHandlerErrors, InferHandlerRequest, InferHandlerResponse } from 'pathstrider/client';

type Route<Handler, Method extends import('pathstrider/client').UppercaseHTTPMethod> = ClientMethod<
  InferHandlerRequest<Handler>,
  InferHandlerResponse<Handler>,
  Method,
  InferHandlerErrors<Handler>
>;

declare module 'pathstrider/routes' {
  interface AppRoutes {
    connect: Route<typeof import("../server/api/index").default, 'CONNECT'>;
    delete: Route<typeof import("../server/api/index").default, 'DELETE'>;
    get: Route<typeof import("../server/api/index").default, 'GET'>;
    head: Route<typeof import("../server/api/index").default, 'HEAD'>;
    options: Route<typeof import("../server/api/index").default, 'OPTIONS'>;
    patch: Route<typeof import("../server/api/index").default, 'PATCH'>;
    post: Route<typeof import("../server/api/index").default, 'POST'>;
    put: Route<typeof import("../server/api/index").default, 'PUT'>;
    query: Route<typeof import("../server/api/index").default, 'QUERY'>;
    trace: Route<typeof import("../server/api/index").default, 'TRACE'>;
    user: {
      get: Route<typeof import("../server/api/user/index.get").default, 'GET'>;
      post: Route<typeof import("../server/api/user/index.post").default, 'POST'>;
    };
  }
}

export {};
